name: flutter_shapes_matching_game
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  provider: ^3.0.0
  flutter_tts: ^2.0.0
  assets_audio_player: ^2.0.13+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/bg1.jpg
    - assets/images/bg2.jpg
    - assets/images/bg3.jpg
    - assets/images/bg4.jpg
    - assets/images/bg5.jpg
    
    - assets/images/1-animals/0.png
    - assets/images/1-animals/1.png
    - assets/images/1-animals/2.png
    - assets/images/1-animals/3.png
    - assets/images/1-animals/4.png
    - assets/images/1-animals/5.png
    - assets/images/1-animals/6.png
    - assets/images/1-animals/7.png
    - assets/images/1-animals/8.png
    - assets/images/1-animals/9.png
    - assets/images/2-dinos/0.png
    - assets/images/2-dinos/1.png
    - assets/images/2-dinos/2.png
    - assets/images/2-dinos/3.png
    - assets/images/2-dinos/4.png
    - assets/images/2-dinos/5.png
    - assets/images/2-dinos/6.png
    - assets/images/2-dinos/7.png
    - assets/images/2-dinos/8.png
    - assets/images/2-dinos/9.png
    - assets/images/3-fruits/0.png
    - assets/images/3-fruits/1.png
    - assets/images/3-fruits/2.png
    - assets/images/3-fruits/3.png
    - assets/images/3-fruits/4.png
    - assets/images/3-fruits/5.png
    - assets/images/3-fruits/6.png
    - assets/images/3-fruits/7.png
    - assets/images/3-fruits/8.png
    - assets/images/3-fruits/9.png
    - assets/images/4-insects/0.png
    - assets/images/4-insects/1.png
    - assets/images/4-insects/2.png
    - assets/images/4-insects/3.png
    - assets/images/4-insects/4.png
    - assets/images/4-insects/5.png
    - assets/images/4-insects/6.png
    - assets/images/4-insects/7.png
    - assets/images/4-insects/8.png
    - assets/images/4-insects/9.png
    - assets/images/5-sea/0.png
    - assets/images/5-sea/1.png
    - assets/images/5-sea/2.png
    - assets/images/5-sea/3.png
    - assets/images/5-sea/4.png
    - assets/images/5-sea/5.png
    - assets/images/5-sea/6.png
    - assets/images/5-sea/7.png
    - assets/images/5-sea/8.png
    - assets/images/5-sea/9.png

    - assets/images/goodjob.gif

    - assets/audios/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

